# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/osc/Cora-Z7-07S-Master.xdc

# Block Designs: bd/aes/aes.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes || ORIG_REF_NAME==aes} -quiet] -quiet

# IP: bd/aes/ip/aes_processing_system7_0_0/aes_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_processing_system7_0_0 || ORIG_REF_NAME==aes_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes/ip/aes_aes_core_0_2/aes_aes_core_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_aes_core_0_2 || ORIG_REF_NAME==aes_aes_core_0_2} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_smc_2/aes_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_smc_2 || ORIG_REF_NAME==aes_axi_smc_2} -quiet] -quiet

# IP: bd/aes/ip/aes_rst_ps7_0_50M_2/aes_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_rst_ps7_0_50M_2 || ORIG_REF_NAME==aes_rst_ps7_0_50M_2} -quiet] -quiet

# XDC: c:/proj/rijndael/rijndael.gen/sources_1/bd/aes/aes_ooc.xdc
